import React from 'react';
import { HelpCircle, CheckCircle2, AlertTriangle, Flame, ShieldAlert, Cpu } from 'lucide-react';
import { useWeather } from '../context/WeatherContext';
import { RiskLevel } from '../types/weather';

export const ExplainabilityCard: React.FC = () => {
  const { nowcast } = useWeather();
  const factors = nowcast?.explainability || [];

  const getSeverityBadge = (severity: RiskLevel) => {
    switch (severity) {
      case 'SEVERE':
        return 'text-rose-400 bg-rose-500/10 border-rose-500/30';
      case 'HIGH':
        return 'text-orange-400 bg-orange-500/10 border-orange-500/30';
      case 'MODERATE':
        return 'text-amber-400 bg-amber-500/10 border-amber-500/30';
      case 'LOW':
      default:
        return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30';
    }
  };

  return (
    <div className="bg-radar-panel border border-radar-border rounded-xl p-4 shadow-lg space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-radar-border pb-3">
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/30 text-emerald-400">
            <Cpu className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-200">
              Why This Risk? (Meteorological Explainability)
            </h2>
            <p className="text-[11px] text-slate-400">
              Physical Thermodynamic &amp; Radar Contributing Factors
            </p>
          </div>
        </div>
        <span className="text-[10px] font-mono text-emerald-400 bg-emerald-950/60 border border-emerald-800 px-2 py-0.5 rounded">
          PHYSICS-BASED
        </span>
      </div>

      {/* Factors List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {factors.map((factor, idx) => (
          <div
            key={idx}
            className="p-3.5 rounded-lg bg-radar-surface/60 border border-radar-border space-y-2 hover:border-slate-700 transition"
          >
            <div className="flex items-center justify-between">
              <span className="font-bold text-xs text-slate-200">
                {factor.name}
              </span>
              <span
                className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded uppercase border ${getSeverityBadge(
                  factor.severity
                )}`}
              >
                {factor.status}
              </span>
            </div>

            <div className="flex items-center gap-2 text-xs font-mono text-sky-300">
              <span className="font-semibold">{factor.metric}</span>
            </div>

            <p className="text-xs text-slate-400 leading-relaxed">
              {factor.description}
            </p>
          </div>
        ))}
      </div>

      <div className="text-[11px] text-slate-500 bg-slate-900/40 p-2.5 rounded-lg border border-slate-800 flex items-center gap-2">
        <HelpCircle className="w-4 h-4 text-sky-400 shrink-0" />
        <span>
          Outputs are generated by synthesizing numerical sounding parameters (CAPE, CIN, 0-6km Bulk Shear) and real-time Doppler radar advection tracking.
        </span>
      </div>
    </div>
  );
};
